
trigger:
- master

  
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    command: 'build'
    Dockerfile: '**/Dockerfile'

- task: CmdLine@2
  inputs:
    script: |
      docker ps -a
      docker image ls
      docker ps
      wget https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
      export WS_DOCKER_SCANCONTAINERS=TRUE
      export WS_DOCKER_CONTAINERINCLUDES=.*
      java -jar wss-unified-agent.jar -d ./ -apikey $(APIKEY) -project DockerTest -product DockerTest