
trigger:
- master

  
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CmdLine@2
  inputs:
    script: |
      sudo rm /usr/local/bin/docker-compose
      sudo apt remove docker-compose
      sudo curl -L "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      sudo chmod +x /usr/local/bin/docker-compose
      docker-compose -v

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'build'

- task: CmdLine@2
  inputs:
    script: |
      docker ps -a
      docker image ls
      docker ps
      wget https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
      export WS_DOCKER_INCLUDES=.*$(Build.Repository.Name).*
      java -jar wss-unified-agent.jar -d ./ -apikey $(APIKEY) -project DockerTest -product $(Build.Repository.Name) -docker.scanImages true

