
trigger:
- main

pool:
  vmImage: 'maven:3.6.3'

steps:
- task: CmdLine@2
  inputs:
    script: |
      wget https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
      java -jar wss-unified-agent.jar -c ./EUA-maven.config -appPath ./target/JavaVulnerableLab.war -d ./ -apikey $(API_KEY) -project JVL -product ADO-Pipeline
