
trigger:
- master

  
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CmdLine@2
  inputs:
    script: |
      docker-compose -v
      
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'build'

- task: CmdLine@2
  inputs:
    script: |
      docker ps -a
      docker image ls
      docker ps
      wget https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
      export WS_DOCKER_INCLUDES=.*$(Build.Repository.Name).*
      java -jar wss-unified-agent.jar -d ./ -apikey $(APIKEY) -project DockerTest -product $(Build.Repository.Name) -docker.scanImages true

