
trigger:
- main

variables: 
  API_KEY: $(apikey)
  
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: WhiteSource@20
  inputs:
    cwd: '$(System.DefaultWorkingDirectory)'
    projectName: '$(Build.Repository.Name)'
    configuration: |
      checkPolicies=true
      forceCheckAllDependencies=true
      forceUpdate=true
      forceUpdate.failBuildOnPolicyViolation=true'