
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
- task: CmdLine@2
  inputs:
    script: |
      wget https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
      java -jar wss-unified-agent.jar -c ./EUA-maven.config -appPath ./target/JavaVulnerableLab.war -d ./ -apikey $(API_KEY) -project JVL -product ADO-Pipeline
