version: "2.4"
services:
  javavulnlab:
    build: .
    ports:
      - 8080:8080
    networks: 
      - front-tier
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - front-tier
networks:
  front-tier:
    driver: bridge
